services:
  app:
    build: .
    container_name: app
    command: [ "gunicorn", "--bind", "0.0.0.0:5000", "wsgi" ]

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/app/static
    ports:
      - "80:80"
    depends_on:
      - app